version: '3.9'

networks:
  net:
    driver: bridge

services:
  chromadb:
    image: chromadb/chroma
    hostname: chromadb
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - "8192:8000"
    networks:
      - net

  postgres:
    image: postgres:14-alpine
    hostname: postgresdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vectoradmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vdbms
    networks:
      - net

  vector-admin:
    container_name: vector-admin
    image: mintplexlabs/vectoradmin
    environment:
      - JWT_SECRET=your-random-string-here
      - DATABASE_CONNECTION_STRING=postgresql://vectoradmin:password@postgresdb:5432/vdbms
    volumes:
      - vectoradmin-backend-storage:/app/backend/storage
    ports:
      - "3001:3001"
    depends_on:
      - chromadb
      - postgres
    networks:
        - net

volumes:
  vectoradmin-backend-storage:
    driver: local
  postgres-data:
    driver: local
  chroma-data:
    driver: local